fixed workflow

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -8,7 +8,21 @@ on:
       - develop
 
 jobs:
+  pr-title-enforcement:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Check PR title
+        run: |
+          if [[ ! ${{ github.event.pull_request.title }} =~ (feature|bug): ]]; then
+            echo "PR title does not follow the required convention. It must start with 'fix:', 'feature:', or 'chore:'."
+            exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
+
   lint-and-unit-test:
+    needs: [pr-title-enforcement]
     name: Lint & Unit Tests
     runs-on: ubuntu-latest
 
@@ -40,6 +54,7 @@ jobs:
           token: ${{ secrets.CODECOV_TOKEN }}
 
   e2e-tests:
+    needs: [pr-title-enforcement]
     name: End-to-End (with mock data) Tests
     runs-on: ubuntu-latest
 
@@ -69,6 +84,7 @@ jobs:
           path: cypress/screenshots
 
   e2e-tests-api:
+    needs: [pr-title-enforcement]
     name: End-to-End (with api) Tests
     runs-on: ubuntu-latest
 
@@ -182,13 +198,3 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
-
-  pr-title-enforcement:
-    runs-on: ubuntu-latest
-    run: |
-      if [[ ! ${{ github.event.pull_request.title }} =~ (feature|bug): ]]; then
-        echo "PR title does not follow the required convention. It must start with 'fix:', 'feature:', or 'chore:'."
-        exit 1
-      fi
-    env:
-    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
